package com.prafullkumar.languagetranslator.utils

object CountriesList {

    val languageList = listOf(
        "Afrikaans" to "🇿🇦",
        "Arabic" to "🇸🇦",
        "Belarusian" to "🇧🇾",
        "Bulgarian" to "🇧🇬",
        "Bengali" to "🇧🇩",
        "Catalan" to "🇪🇸",
        "Czech" to "🇨🇿",
        "Welsh" to "🏴",
        "Danish" to "🇩🇰",
        "German" to "🇩🇪",
        "Greek" to "🇬🇷",
        "English" to "🏴",
        "Esperanto" to "🌍",
        "Spanish" to "🇪🇸",
        "Estonian" to "🇪🇪",
        "Persian" to "🇮🇷",
        "Finnish" to "🇫🇮",
        "French" to "🇫🇷",
        "Irish" to "☘️",
        "Galician" to "🇪🇸",
        "Gujarati" to "🇮🇳",
        "Hebrew" to "🇮🇱",
        "Hindi" to "🇮🇳",
        "Croatian" to "🇭🇷",
        "Haitian" to "🇭🇹",
        "Hungarian" to "🇭🇺",
        "Indonesian" to "🇮🇩",
        "Icelandic" to "🇮🇸",
        "Italian" to "🇮🇹",
        "Japanese" to "🇯🇵",
        "Georgian" to "🇬🇪",
        "Kannada" to "🇮🇳",
        "Korean" to "🇰🇷",
        "Lithuanian" to "🇱🇹",
        "Latvian" to "🇱🇻",
        "Macedonian" to "🇲🇰",
        "Marathi" to "🇮🇳",
        "Malay" to "🇲🇾",
        "Maltese" to "🇲🇹",
        "Dutch" to "🇳🇱",
        "Norwegian" to "🇳🇴",
        "Polish" to "🇵🇱",
        "Portuguese" to "🇵🇹",
        "Romanian" to "🇷🇴",
        "Russian" to "🇷🇺",
        "Slovak" to "🇸🇰",
        "Slovenian" to "🇸🇮",
        "Albanian" to "🇦🇱",
        "Swedish" to "🇸🇪",
        "Swahili" to "🇰🇪",
        "Tamil" to "🇮🇳",
        "Telugu" to "🇮🇳",
        "Thai" to "🇹🇭",
        "Tagalog" to "🇵🇭",
        "Turkish" to "🇹🇷",
        "Ukrainian" to "🇺🇦",
        "Urdu" to "🇵🇰",
        "Vietnamese" to "🇻🇳",
        "Chinese" to "🇨🇳"
    )
}